name: Auto Hunt by @prakashchand72
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOMAIN: 'clientis.ch'

jobs:
  subdomains:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 
    
    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
      shell: bash

    - name: Run Subfinder
      run: |
        subfinder -d $DOMAIN -o subfinder_output.txt
      shell: bash
      
    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: Subdomains results
        path: |
          subfinder_output.txt
  HTTPX:
    runs-on: ubuntu-latest
    needs: subdomains
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: Subdomains results
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 

    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest 
      shell: bash

    - name: HTTPX_Detailed 
      run: |
        cat subfinder_output.txt | httpx -sc -title -server -fr -probe | tee -a detailed_httpx.txt
      shell: bash
    - name: HTTPX_Live for endpoint
      run: | 
        cat subfinder_output.txt | httpx -mc 200 | tee -a 200httpx.txt
      shell: bash
    - name: httpx for all - no filtering
      run: |
        cat subfinder_output.txt | httpx | tee -a normalhttpx.txt
      shell: bash 

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: HTTPX results
        path: |
          detailed_httpx.txt
          200httpx.txt
          normalhttpx.txt

  EndPonts-Waybackurls:
    runs-on: ubuntu-latest
    needs: HTTPX
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: HTTPX results
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 

    - name: Install Required Tools 
      run: |
        go install github.com/tomnomnom/waybackurls@latest
      shell: bash

    - name: Gathering Endpoints 
      run: |
        cat 200httpx.txt | waybackurls > waybackurls.txt
      shell: bash

    - name: Split the endpoint in 10 equal chunks
      run: |
        split -l $(( $(wc -l < waybackurls.txt) / 10 + 1)) waybackurls.txt split_ -a 1 -d --additional-suffix=.txt
      shell: bash

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: endpoints results
        path: |
          waybackurls.txt
          split_0.txt
          split_1.txt
          split_2.txt
          split_3.txt
          split_4.txt
          split_5.txt
          split_6.txt
          split_7.txt
          split_8.txt
          split_9.txt

  HostHeader_Injection-1:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_0.txt injection1.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection1.txt
  HostHeader_Injection-2:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_1.txt injection2.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection2.txt
          
  HostHeader_Injection-3:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_2.txt injection3.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection3.txt

  HostHeader_Injection-4:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_3.txt injection4.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection4.txt

  HostHeader_Injection-5:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_4.txt injection5.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection5.txt

  HostHeader_Injection-6:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_5.txt injection6.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection6.txt

  HostHeader_Injection-7:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_6.txt injection7.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection7.txt

  HostHeader_Injection-8:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_7.txt injection8.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection8.txt

  HostHeader_Injection-9:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_8.txt injection9.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection9.txt

  HostHeader_Injection-10:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh split_9.txt injection10.txt

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          injection10.txt

  Secret-Finder:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install Required Tools 
      run: |
        sudo apt-get -y install python3 python3-pip
        sudo pip3 install requests argparse dnspython
        git clone https://github.com/m4ll0k/SecretFinder ~/SecretFinder
        pip3 install -r ~/SecretFinder/requirements.txt
      shell: bash

    - name: Secret Finder by analyzing js file   
      run: |
        grep -iE '\.js$' waybackurls.txt > endpoints_with_js.txt
        cat endpoints_with_js.txt | while read js ; do python3 ~/SecretFinder/SecretFinder.py -i $js -o cli | tee -a secretfinder.txt;done
      shell: bash

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: secret-finder results
        path: |
          secretfinder.txt
        
